configure-private-chart-operator
giantswarm/cluster-apps-operator pull request #298
Opened 2022-11-10 16:16 UTC by calvix

## Checklist

- [ ] Update changelog in CHANGELOG.md.

2022-11-15 11:58 UTC, calvix commented on service/controller/resource/clusterconfigmap/types.go
> +	ExternalDNSIP *string             `json:"externalDNSIP,omitempty"`
using pointer so we can still  leverage `omitEmpty` but also be able to specify empty string which will override default chart value in `chart-operator` helm chart

2022-11-17 09:03 UTC, fiunchinho approved these changes
Small suggestion, LGTM otherwise.

2022-11-17 09:03 UTC, fiunchinho requested changes
Wait no, it's missing a changelog update.

2022-11-17 09:20 UTC, calvix commented
changelog fixed

2022-11-17 09:33 UTC, calvix commented
@fiunchinho happy with changelog?

2022-11-17 09:39 UTC, fiunchinho approved these changes

2022-11-17 09:39 UTC, merged