Migrate CAPI CRDs from v1alpha4 to v1beta1
giantswarm/cluster-apps-operator pull request #349
Opened 2023-04-12 12:06 UTC by fiunchinho

Towards https://github.com/giantswarm/roadmap/issues/2350

## Checklist

- [X] Update changelog in CHANGELOG.md.

2023-04-13 07:10 UTC, AndiDog requested changes

2023-04-13 07:10 UTC, AndiDog commented on service/collector/cluster_test.go
> +	capiv1alpha4 "sigs.k8s.io/cluster-api/api/v1beta1"
```suggestion
	capi "sigs.k8s.io/cluster-api/api/v1beta1"
```

2023-04-17 08:18 UTC, AndiDog approved these changes

2023-04-17 08:24 UTC, uvegla approved these changes

2023-04-17 08:24 UTC, merged